### ISSUE TITLE
Movies view sure could use some CSS love

### ISSUE THREAD

**Issue by daniel-salin** [chas-academy/09-imdb-clone-team-genius#108]
<img width="200" src="https://www.pubhist.com/works/07/large/joos_craesbeeck_man_surprised.jpg" />

**Comment by daniel-salin** [comment]
<img width="200" src="https://www.pubhist.com/works/07/large/joos_craesbeeck_man_surprised.jpg" />

**Comment by ChristianBlom84** [comment]
I'll take a crack at this. I want to try embedding the trailers on the movie page as well.
