### ISSUE TITLE
Restructure backend to reflect using TMDb API.

### ISSUE THREAD

**Issue by ChristianBlom84** [chas-academy/09-imdb-clone-team-genius#14]

**Comment by daniel-salin** [comment]
Basic migrations for reviews, user and comments up on "reviews_comments_migrations" branch

**Comment by daniel-salin** [comment]
updated "reviews_comments_migrations" branch with Watchlist according to updated ERD

**Comment by daniel-salin** [comment]
List view now renders the seeded movies in watchlist correctly, added an id parameter for route. That being said the watchlist generated for each user is currently identical so list/1 gives the same two movies as list/2
