### ISSUE TITLE
Caching for reviews causes reviews to not render

### ISSUE THREAD

**Issue by fredbellinder** [chas-academy/09-imdb-clone-team-genius#147]
Tried removing the caching for reviews in movie controller and reviews render as intended. Consider removing/altering the caching for reviews.

**Comment by ChristianBlom84** [comment]
Can you provide more details? Are you saying a new review isn't seen? Or a new review that you just approved? Reviews are cached for 10 hours, the cache for the user's and the specific movie is cleared whenever someone writes a new review.

If a review is approved by a moderator and no new reviews are written by the user it won't be seen as approved for 10 hours. I thought that was reasonable and not a big issue. Maybe we should lower the cache time to 1-2 hours?
