### ISSUE TITLE
Hotfix needed, administrate reviews/comments not rendering on dashboard. Related to permissions

### ISSUE THREAD

**Issue by daniel-salin** [chas-academy/09-imdb-clone-team-genius#149]
hasPermissions('browse_reviews')
hasPermissions('browse_comments')

Does not work, probably since the permissions table seeder did not include them. No idea why this suddenly became an issue since it has worked before.

**Comment by ChristianBlom84** [comment]
Works for me, did you check the role_id on the user you're logged in as? It defaults to 2, which is a normal user that doesn't have permission.

**Comment by ChristianBlom84** [comment]
There could be an issue if you've done a migrate:fresh and didn't seed the Voyager data. If you haven't, maybe try runnin php artisan db:seed --class=VoyagerDatabaseSeeder?

**Comment by ChristianBlom84** [comment]
Closing this, the issue is BREAD need to be added to the tables in Voyager.
